apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitor-backend
  namespace: prod
  labels:
    app: visitor-backend
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visitor-backend
      environment: prod
  template:
    metadata:
      labels:
        app: visitor-backend
        environment: prod
    spec:
      containers:
      - name: backend
        image: astin75/visitor-backend:2025061810
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: visitor-backend-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: visitor-backend-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi