apiVersion: v1
kind: Service
metadata:
  name: visitor-backend-service
  namespace: prod
  labels:
    app: visitor-backend
    environment: prod
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31080
    protocol: TCP
    name: http
  selector:
    app: visitor-backend
    environment: prod