apiVersion: v1
kind: Service
metadata:
  name: visitor-backend-service
  namespace: prod
  labels:
    app: visitor-backend
    environment: prod
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: visitor-backend
    environment: prod
---
apiVersion: v1
kind: Service
metadata:
  name: visitor-frontend-service
  namespace: prod
  labels:
    app: visitor-frontend
    environment: prod
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: visitor-frontend
    environment: prod