apiVersion: v1
kind: Service
metadata:
  name: visitor-frontend-service
  namespace: dev
  labels:
    app: visitor-frontend
    environment: dev
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30030
    protocol: TCP
    name: http
  selector:
    app: visitor-frontend
    environment: dev