apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
---
# ArgoCD 설치를 위한 기본 매니페스트
# 실제 운영에서는 공식 설치 매니페스트를 사용하세요:
# kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-tutorial-info
  namespace: argocd
data:
  info: |
    ArgoCD 설치 방법:
    1. 이 파일을 적용하여 namespace와 기본 설정 생성
    2. 공식 매니페스트로 ArgoCD 설치:
       kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    3. 초기 admin 비밀번호 확인:
       kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
    4. 포트 포워딩으로 접속:
       kubectl port-forward svc/argocd-server -n argocd 8080:443