apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-config
  namespace: dev
  labels:
    app: sample-app
    environment: dev
data:
  app.properties: |
    environment=development
    debug=true
    log_level=debug
  
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
        }
    }