apiVersion: v1
kind: Service
metadata:
  name: visitor-app-service
  namespace: dev
  labels:
    app: visitor-app
    environment: dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
    name: frontend
  - port: 8000
    targetPort: 8000
    nodePort: 30001
    protocol: TCP
    name: backend
  selector:
    app: visitor-app
    environment: dev