apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/astin75/gitops
    targetRevision: prod
    path: argocd/applications-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true