apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visitor-frontend-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/astin75/gitops
    targetRevision: HEAD
    path: applications/dev/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true