apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitor-frontend
  namespace: prod
  labels:
    app: visitor-frontend
    environment: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: visitor-frontend
      environment: prod
  template:
    metadata:
      labels:
        app: visitor-frontend
        environment: prod
    spec:
      containers:
      - name: frontend
        image: astin75/visitor-frontend:202506151630
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://visitor-backend-service:8000"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"