apiVersion: v1
kind: Service
metadata:
  name: visitor-frontend-service
  namespace: prod
  labels:
    app: visitor-frontend
    environment: prod
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 31030
    protocol: TCP
    name: http
  selector:
    app: visitor-frontend
    environment: prod