name: PR Check

on:
  pull_request:
    branches:
      - dev
      - prod
    paths:
      - 'app/**'

env:
  DOCKER_REGISTRY: astin75

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if service changed
        id: check
        run: |
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q "app/${{ matrix.service }}/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.check.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (test only)
        if: steps.check.outputs.changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./app/${{ matrix.service }}
          push: false
          tags: |
            ${{ env.DOCKER_REGISTRY }}/visitor-${{ matrix.service }}:pr-${{ github.event.pull_request.number }}

      - name: Comment PR
        if: steps.check.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ ${{ matrix.service }} Docker build successful!'
            })